---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(knitr)
library(scales)
library(xtable)
library(broom)
```
# load data
```{r}
dExpectation = read_csv('./expectation/expectations-by-condition.csv') 
dTruth = read_csv('./expectation/ground-truth-by-condition.csv') 
```

# word level response
```{r}
# Z score averages of expectation rating and actual percent matches (across participants) and compare
expectation <- aggregate(dExpectation[, 2], list(dExpectation$word), mean) %>% 
  mutate(zscore = (sliderResponse - mean(sliderResponse))/sd(sliderResponse)) %>%
  rename(word = "Group.1", avgExpectation = sliderResponse)

truth <-  aggregate(dTruth[, 2], list(dTruth$word), mean) %>% 
  mutate(zscore = (groundTruth - mean(groundTruth))/sd(groundTruth))
```
# plot word level responses (averaged over participants + z-scored)
```{r}
scatter.smooth(x=expectation$zscore, y=truth$zscore, xlab="Average expecation rating", ylab="Average percent agreement", main="Expected agreement vs. actual agreement")
```
# Compare DeltaE among participants' block 2 responses against average slider rating
```{r}
dDeltaE = read_csv('./deltaE/sorted-deltaE-CIE2000-block2.csv') 

# zscoring:
deltaE <- dDeltaE[order(dDeltaE$word),] %>%
  mutate(zscore = (deltaE - mean(deltaE))/sd(deltaE))
# averaging slider + zscoring
expectation <- aggregate(dExpectation[, 2], list(dExpectation$word), mean) %>%
  rename(word = "Group.1", avgExpectation = sliderResponse) %>%
  mutate(zscore = (avgExpectation - mean(avgExpectation))/sd(avgExpectation))

# plot
scatter.smooth(x=expectation$zscore, y=deltaE$zscore, xlab="Average expecation rating", ylab="Average Delta E among block2 repsonses", main="Expected agreement vs. average Delta E")

# correlation
cor.test(expectation$zscore, deltaE$zscore)
```

# Expectation ratings box plot
```{r}
library("ggpubr")
ggboxplot(dExpectation, y = "sliderResponse", main= "Expected Agreement by Condition",
          color = "condition", palette = c("#D8644B", "#4B7CD8"),
          order = c("concrete", "abstract"), ylim = c(0, 100),
          ylab = "% of population expected to share one's color association", xlab="words")
```

# Ground truth boxplot
```{r}
ggboxplot(dTruth, y = "groundTruth", main= "Actual Agreement by Condition",
          color = "condition", palette = c("#D8644B", "#4B7CD8"),
          order = c("concrete", "abstract"), ylim = c(0, 100),
          ylab = "% of population actually sharing color association", xlab="words")
```

# plotting expectation for top and bottom 10 words individually
```{r}
selectedWords <- filter(dExpectation, word %in% c("lemon", "sun", "tomato", "fire", "apple", "spinach", "vegetable", "tree", "daffodil"))

boxplot(sliderResponse~word, data=selectedWords, main="Expected Agreement",
   xlab="Words", ylab="% of population expected to share one's color association", ylim = c(0, 100))
```

# plotting actual agreement for top 10 words individually
```{r}
selectedWords <- filter(dTruth, word %in% c("lemon", "sun", "tomato", "fire", "apple", "spinach", "vegetable", "tree", "daffodil"))

boxplot(groundTruth~word, data=selectedWords, main="Actual Agreement",
   xlab="Words", ylab="% of population actually sharing association", ylim = c(0, 100))
```


<!-- # compare expectation to entropy for each word -->
<!-- ```{r} -->

<!-- filtered <- d %>% -->
<!--   mutate(sliderResponse = as.numeric(sliderResponse)) -->
<!-- # calculate mean per group  -->
<!-- avgExpectation <- aggregate(filtered$sliderResponse, by = list(filtered$word), FUN = mean) -->

<!-- # load and format entropy data -->
<!-- f = read_csv('./entropy/sorted-entropies-all-both.csv')  -->

<!-- f = f %>% -->
<!--   mutate(both = as.numeric(both)) -

<!-- scatter.smooth(x=f$both, y=avgExpectation$x, xlab = "Entropy of participants' color associations for all words", ylab = "Average % of population expected to share one's color association") -->
<!-- ``` -->

<!-- # attempt to combine entropy ratings and slider responses to do a mixed effect model with subject as the random effect -->
<!-- ```{r} -->
<!-- library(lme4) -->

<!-- # NEED TO JOIN DATAFRAMES -->
<!-- mixedModel <- lmer(filtered$entropy ~ d$sliderResponse  + (1|d$aID)) -->
<!-- summary(mixedModel) -->
<!-- ``` -->


