---
title: "R Notebook"
output: html_notebook
---

# Import libraries

```{r}
library(tidyverse)
library(knitr)
library(xtable)
```

# Import data

```{r}
d.raw = read_csv('../data/norming/dataFromMongo.csv') 
```
Check how many people failed catch trials

```{r results='asis'}
d.raw %>%
  group_by(aID) %>%
  unite(trial_chunk, trial_type, condition) %>%
  filter(trial_index == last(trial_index)) %>%
  group_by(trial_chunk) %>%
  tally() %>%
  kable() %>%
  cat(sep = '\n')
```
Only include participants who completed exactly 89 color-picker trials (80 words + 9 practice/catch)

```{r}
d.raw = read_csv('../data/norming/dataFromMongo.csv') 

complete_games = d.raw %>%
  filter(trial_type == 'color-picker') %>%
  group_by(aID) %>%
  tally() %>%
  filter(n == 89) %>% 
  pull(aID)

cat('including', length(complete_games), 'complete games')

d <- d.raw %>%
  filter(aID %in% complete_games)

d %>%
  group_by(wordSetID, aID) %>%
  tally() %>%
  group_by(wordSetID) %>%
  tally()
```

```{r}
library(scales)
d %>%
  filter(trial_type == 'color-picker') %>%
  mutate(hex = rgb(response_r/255, response_g/255, response_b/255)) %>%
  group_by(word) %>%
  do(ggsave(.$word, device = 'png', plot = show_col(.$hex, labels = F)))
```
